"""Record a ratchet conversation as interop vectors for the JavaScript implementation.

The mirror of frontend/scripts/generate-ratchet-vectors.mjs. Both directions are checked
because a shared bug in one implementation's *encoder* would go unnoticed if only that
side ever produced the vectors.

    cd backend && python scripts/generate_ratchet_vectors.py \\
        > ../frontend/src/crypto/vectors/ratchet_py_vectors.json
"""
from __future__ import annotations

import base64
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.crypto import ratchet  # noqa: E402
from app.crypto.ratchet import X25519PrivateKey  # noqa: E402

CHANNEL_ID = "interop-channel-py"
ALICE_ID = "alice-uuid"
BOB_ID = "bob-uuid"
EPOCH = 0


def b64(value: bytes) -> str:
    return base64.b64encode(value).decode("ascii")


def recording_keygen(pool: list[bytes], used: list[str]):
    index = {"value": 0}

    def keygen() -> ratchet.KeyPair:
        position = index["value"]
        if position >= len(pool):
            raise AssertionError("ratchet consumed more keypairs than the pool holds")
        index["value"] += 1
        secret = pool[position]
        private = X25519PrivateKey.from_private_bytes(secret)
        used.append(b64(secret))
        return ratchet.KeyPair(secret=secret, public=private.public_key().public_bytes_raw())

    return keygen


def main() -> None:
    shared_secret = os.urandom(32)
    bob_identity_secret = os.urandom(32)
    bob_identity = ratchet.KeyPair(
        secret=bob_identity_secret,
        public=X25519PrivateKey.from_private_bytes(bob_identity_secret)
        .public_key()
        .public_bytes_raw(),
    )

    alice_pool = [os.urandom(32) for _ in range(8)]
    bob_pool = [os.urandom(32) for _ in range(8)]
    alice_used: list[str] = []
    bob_used: list[str] = []

    alice = ratchet.init_sender(
        shared_secret, bob_identity.public, keygen=recording_keygen(alice_pool, alice_used)
    )
    bob = ratchet.init_receiver(
        shared_secret, bob_identity, keygen=recording_keygen(bob_pool, bob_used)
    )

    script = [
        ("alice", "first from the aircraft side"),
        ("alice", "second from the aircraft side"),
        ("bob", "reply from the console"),
        ("alice", "after the flip"),
        ("alice", "still after the flip"),
        ("bob", "second reply"),
        ("alice", "final"),
    ]

    messages = []
    for origin, plaintext in script:
        sender = alice if origin == "alice" else bob
        receiver = bob if origin == "alice" else alice
        sender_id = ALICE_ID if origin == "alice" else BOB_ID

        envelope = ratchet.encrypt(
            sender,
            plaintext.encode(),
            sender_id=sender_id,
            channel_id=CHANNEL_ID,
            epoch=EPOCH,
        )
        round_tripped = ratchet.decrypt(
            receiver, envelope, sender_id=sender_id, channel_id=CHANNEL_ID, epoch=EPOCH
        )
        assert round_tripped.decode() == plaintext, "generator failed its own round trip"

        messages.append(
            {
                "from": origin,
                "sender_id": sender_id,
                "plaintext": plaintext,
                "envelope": b64(envelope),
                "epoch": EPOCH,
            }
        )

    json.dump(
        {
            "description": (
                "Generated by backend/scripts/generate_ratchet_vectors.py. Replayed by "
                "the JavaScript implementation to prove wire compatibility."
            ),
            "produced_by": "python",
            "channel_id": CHANNEL_ID,
            "alice_id": ALICE_ID,
            "bob_id": BOB_ID,
            "shared_secret": b64(shared_secret),
            "bob_identity_secret": b64(bob_identity.secret),
            "bob_identity_public": b64(bob_identity.public),
            "alice_keygen_queue": alice_used,
            "bob_keygen_queue": bob_used,
            "messages": messages,
        },
        sys.stdout,
        indent=2,
    )
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
