#!/bin/bash
#
# Final deploy step for vishal.kovaihost.cloud: write the production .env, then start
# the service.
#
# This is split out from the rest of the deployment because it is the only step that
# creates credentials. It generates the database password and the JWT secret ON THE
# SERVER, uses them in place, and never prints them -- so the values do not end up in a
# terminal transcript, a log, or an agent's context.
#
# Everything else (liboqs, the venv, nginx, TLS, the systemd unit) is already in place.
#
# Run it on the server as root:
#
#     ssh -i ~/.ssh/prahari_deploy root@203.57.85.138 'bash -s' < deploy/provision-env.sh
#
# It is safe to re-run: it rotates both secrets and restarts the service.

set -euo pipefail

APP=/opt/prahari/app/backend
PY=$APP/.venv/bin/python

[ -x "$PY" ] || { echo "FATAL: venv missing at $PY" >&2; exit 1; }

DBPASS="$("$PY" -c 'import secrets; print(secrets.token_urlsafe(24))')"
JWTSEC="$("$PY" -c 'import secrets; print(secrets.token_urlsafe(48))')"

# The prahari database is empty, so rotating the role password breaks nothing.
su - postgres -c "psql -q -c \"ALTER ROLE prahari WITH PASSWORD '${DBPASS}'\"" >/dev/null
echo "[1/5] database role password set"

umask 077
cat > "$APP/.env" <<EOF
# Generated by deploy/provision-env.sh. Contains live secrets -- do not commit or copy.
ENVIRONMENT=production

DATABASE_URL=postgresql+asyncpg://prahari:${DBPASS}@127.0.0.1:5432/prahari
DB_POOL_SIZE=5
DB_MAX_OVERFLOW=5

JWT_SECRET=${JWTSEC}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_TTL_MINUTES=60

# Same-origin deployment: nginx serves the app and the API from one host, so this is
# only a belt-and-braces value -- there is no cross-origin request to approve.
CORS_ORIGINS=https://vishal.kovaihost.cloud

# Constant-time ML-KEM. The app refuses to start in production with anything else.
PQC_BACKEND=liboqs
REKEY_AFTER_MESSAGES=100
REKEY_AFTER_MINUTES=15
MAX_MESSAGE_BYTES=131072

# Sized for this 2-core box, not for the 1000-endpoint target.
MAX_WEBSOCKET_CONNECTIONS=200

POLYGON_RPC_URL=
ANCHOR_CONTRACT_ADDRESS=
ANCHOR_PRIVATE_KEY=
EOF

chown prahari:prahari "$APP/.env"
chmod 600 "$APP/.env"
echo "[2/5] .env written ($(stat -c %a "$APP/.env") $(stat -c %U "$APP/.env"))"

# Prove the credential works before handing it to systemd, so a failure here is a clear
# database error rather than an opaque service crash-loop.
PGPASSWORD="$DBPASS" psql -h 127.0.0.1 -U prahari -d prahari -tAc 'select 1' >/dev/null
echo "[3/5] database authentication verified"

unset DBPASS JWTSEC

systemctl enable --now prahari
echo "[4/5] service enabled and started"

sleep 6
systemctl is-active --quiet prahari || { systemctl status prahari --no-pager -l | tail -30; exit 1; }
curl -fsS -o /dev/null -m 10 http://127.0.0.1:8801/health
echo "[5/5] backend healthy on 127.0.0.1:8801"

echo
echo "Done. https://vishal.kovaihost.cloud should now be fully live."
