"""Double Ratchet, wire-compatible with the browser implementation.

This is the aircraft's half of the same protocol the console speaks. It exists so the UAV
link is not the weaker path: the README's claim that both deployments run one protocol
only holds if the ratchet reaches the bridge too.

Every constant here is load-bearing for interoperability -- the KDF labels, the chain
constants, the big-endian header layout and the AAD framing must match
``frontend/src/crypto/ratchet.js`` exactly. ``tests/test_ratchet_interop.py`` checks that
against vectors generated by the JavaScript implementation rather than trusting this
comment.

Design notes live in the JavaScript module; the security properties and the limits of the
post-quantum claim are identical and are not repeated here.
"""
from __future__ import annotations

import hmac
import os
import struct
from dataclasses import dataclass, field
from hashlib import sha256
from typing import Callable, Dict, Optional, Tuple

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.asymmetric.x25519 import (
    X25519PrivateKey,
    X25519PublicKey,
)

ENVELOPE_VERSION = 2
ROOT_INFO = b"prahari/ratchet/root/v1"

MESSAGE_KEY_CONSTANT = b"\x01"
CHAIN_KEY_CONSTANT = b"\x02"

RATCHET_PUBLIC_BYTES = 32
COUNTER_BYTES = 4
HEADER_BYTES = RATCHET_PUBLIC_BYTES + COUNTER_BYTES * 2
NONCE_BYTES = 12
TAG_BYTES = 16

MAX_SKIP = 1000
MAX_STORED_SKIPPED = 2000


class RatchetError(Exception):
    def __init__(self, message: str, code: str = "ratchet_error") -> None:
        super().__init__(message)
        self.code = code


@dataclass
class KeyPair:
    secret: bytes
    public: bytes

    @classmethod
    def generate(cls) -> "KeyPair":
        private = X25519PrivateKey.generate()
        return cls(
            secret=private.private_bytes_raw(),
            public=private.public_key().public_bytes_raw(),
        )


@dataclass
class Header:
    ratchet_public: bytes
    previous_chain_length: int
    message_number: int

    def to_bytes(self) -> bytes:
        return self.ratchet_public + struct.pack(
            "!II", self.previous_chain_length, self.message_number
        )

    @classmethod
    def from_bytes(cls, raw: bytes) -> "Header":
        if len(raw) != HEADER_BYTES:
            raise RatchetError("bad header length", "bad_header")
        previous, number = struct.unpack("!II", raw[RATCHET_PUBLIC_BYTES:])
        return cls(raw[:RATCHET_PUBLIC_BYTES], previous, number)


@dataclass
class RatchetState:
    root_key: bytes
    send_ratchet: KeyPair
    remote_ratchet_public: Optional[bytes] = None
    sending_chain_key: Optional[bytes] = None
    receiving_chain_key: Optional[bytes] = None
    sent: int = 0
    received: int = 0
    previous_chain_length: int = 0
    skipped: Dict[Tuple[bytes, int], bytes] = field(default_factory=dict)
    #: Test seam. Vectors replay a recorded conversation, which is only possible if the
    #: ephemeral keypairs can be supplied instead of generated.
    keygen: Callable[[], KeyPair] = KeyPair.generate


def _hkdf_sha256(salt: bytes, ikm: bytes, info: bytes, length: int) -> bytes:
    """RFC 5869. Implemented directly to keep it obviously identical to WebCrypto."""
    prk = hmac.new(salt, ikm, sha256).digest()
    output = b""
    block = b""
    counter = 1
    while len(output) < length:
        block = hmac.new(prk, block + info + bytes([counter]), sha256).digest()
        output += block
        counter += 1
    return output[:length]


def _kdf_root_key(root_key: bytes, dh_output: bytes) -> Tuple[bytes, bytes]:
    derived = _hkdf_sha256(root_key, dh_output, ROOT_INFO, 64)
    return derived[:32], derived[32:]


def _advance_chain(chain_key: bytes) -> Tuple[bytes, bytes]:
    message_key = hmac.new(chain_key, MESSAGE_KEY_CONSTANT, sha256).digest()
    next_chain_key = hmac.new(chain_key, CHAIN_KEY_CONSTANT, sha256).digest()
    return message_key, next_chain_key


def _dh(secret: bytes, public: bytes) -> bytes:
    return X25519PrivateKey.from_private_bytes(secret).exchange(
        X25519PublicKey.from_public_bytes(public)
    )


def build_aad(*, sender_id: str, channel_id: str, epoch: int, header: bytes) -> bytes:
    return (
        b"prahari-v%d|" % ENVELOPE_VERSION
        + sender_id.encode("utf-8")
        + b"|"
        + channel_id.encode("utf-8")
        + b"|"
        + str(epoch).encode("ascii")
        + b"|"
        + header
    )


def init_sender(
    shared_secret: bytes,
    remote_ratchet_public: bytes,
    *,
    keygen: Callable[[], KeyPair] = KeyPair.generate,
) -> RatchetState:
    keypair = keygen()
    root_key, chain_key = _kdf_root_key(
        shared_secret, _dh(keypair.secret, remote_ratchet_public)
    )
    return RatchetState(
        root_key=root_key,
        send_ratchet=keypair,
        remote_ratchet_public=remote_ratchet_public,
        sending_chain_key=chain_key,
        keygen=keygen,
    )


def init_receiver(
    shared_secret: bytes,
    own_ratchet_keypair: KeyPair,
    *,
    keygen: Callable[[], KeyPair] = KeyPair.generate,
) -> RatchetState:
    return RatchetState(
        root_key=shared_secret,
        send_ratchet=own_ratchet_keypair,
        keygen=keygen,
    )


def _dh_ratchet(state: RatchetState, header: Header) -> None:
    state.previous_chain_length = state.sent
    state.sent = 0
    state.received = 0
    state.remote_ratchet_public = header.ratchet_public

    state.root_key, state.receiving_chain_key = _kdf_root_key(
        state.root_key, _dh(state.send_ratchet.secret, state.remote_ratchet_public)
    )
    state.send_ratchet = state.keygen()
    state.root_key, state.sending_chain_key = _kdf_root_key(
        state.root_key, _dh(state.send_ratchet.secret, state.remote_ratchet_public)
    )


def _skip_message_keys(state: RatchetState, until: int) -> None:
    if state.receiving_chain_key is None:
        return
    if until - state.received > MAX_SKIP:
        raise RatchetError(
            f"refusing to derive more than {MAX_SKIP} skipped message keys",
            "too_many_skipped",
        )
    while state.received < until:
        message_key, state.receiving_chain_key = _advance_chain(state.receiving_chain_key)
        state.skipped[(bytes(state.remote_ratchet_public), state.received)] = message_key
        state.received += 1
    # dict preserves insertion order, so the oldest retained key is the first key.
    while len(state.skipped) > MAX_STORED_SKIPPED:
        del state.skipped[next(iter(state.skipped))]


def encrypt(state: RatchetState, plaintext: bytes, *, sender_id: str, channel_id: str, epoch: int) -> bytes:
    if state.sending_chain_key is None:
        raise RatchetError(
            "no sending chain yet: this side must receive a message before it can send",
            "no_sending_chain",
        )
    message_key, state.sending_chain_key = _advance_chain(state.sending_chain_key)
    header = Header(state.send_ratchet.public, state.previous_chain_length, state.sent).to_bytes()
    state.sent += 1

    nonce = os.urandom(NONCE_BYTES)
    aad = build_aad(sender_id=sender_id, channel_id=channel_id, epoch=epoch, header=header)
    ciphertext = AESGCM(message_key).encrypt(nonce, plaintext, aad)
    return bytes([ENVELOPE_VERSION]) + header + nonce + ciphertext


def decrypt(state: RatchetState, envelope: bytes, *, sender_id: str, channel_id: str, epoch: int) -> bytes:
    if len(envelope) < 1 + HEADER_BYTES + NONCE_BYTES + TAG_BYTES:
        raise RatchetError("truncated envelope", "bad_envelope")
    if envelope[0] != ENVELOPE_VERSION:
        raise RatchetError(f"unsupported envelope version {envelope[0]}", "bad_envelope")

    header_bytes = envelope[1 : 1 + HEADER_BYTES]
    nonce = envelope[1 + HEADER_BYTES : 1 + HEADER_BYTES + NONCE_BYTES]
    ciphertext = envelope[1 + HEADER_BYTES + NONCE_BYTES :]
    header = Header.from_bytes(header_bytes)
    aad = build_aad(sender_id=sender_id, channel_id=channel_id, epoch=epoch, header=header_bytes)

    stored = (bytes(header.ratchet_public), header.message_number)
    if stored in state.skipped:
        try:
            plaintext = AESGCM(state.skipped[stored]).decrypt(nonce, ciphertext, aad)
        except InvalidTag:
            raise RatchetError("authentication failed", "auth_failed") from None
        # Dropped only once the message has actually authenticated: discarding it on a
        # forgery would lose the real message for good.
        del state.skipped[stored]
        return plaintext

    is_new_ratchet = (
        state.remote_ratchet_public is None
        or header.ratchet_public != state.remote_ratchet_public
    )
    if is_new_ratchet:
        if state.receiving_chain_key is not None:
            _skip_message_keys(state, header.previous_chain_length)
        _dh_ratchet(state, header)

    _skip_message_keys(state, header.message_number)

    message_key, next_chain_key = _advance_chain(state.receiving_chain_key)
    try:
        plaintext = AESGCM(message_key).decrypt(nonce, ciphertext, aad)
    except InvalidTag:
        # State is left untouched so a forged message cannot advance the chain past the
        # legitimate one and strand it.
        raise RatchetError("authentication failed", "auth_failed") from None

    state.receiving_chain_key = next_chain_key
    state.received += 1
    return plaintext
